POST http://localhost:3000/authorization/
Content-Type: application/json

{
    "username" : "username",
    "password" : "password"
}

###

POST http://localhost:3000/saveDocument
Content-Type: application/json

{
    "title" : "Testdokument nummer 3",
    "content" : "<h1>Goodbye World</h1>"
}

###

POST http://localhost:3000/updateDocument
Content-Type: application/json

{
    "id" : 1,
    "content" : "Jag är uppdaterad, tjoho!"
}

###

GET http://localhost:3000/getDocuments